/**
 * Deterministic Generated Exercise GIFs Registry
 * Autogenerated by scripts/generate-exercise-gifs.ts (v1.0.0)
 *
 * Provides two-frame animated GIF demonstrations compiled ahead-of-time
 * from public/exercises/ source imagery.
 */

export interface GeneratedExerciseGifRecord {
  replyfExerciseId: string;
  canonicalExerciseName: string;
  canonicalSlug: string;
  sourceType: 'generated-gif';
  sourceImages: [string, string];
  mediaUrl: string;
  frameCount: 2;
  frameDurationMs: number;
  sourceHash: string;
  generatorVersion: string;
  width: number;
  height: number;
  fileSizeBytes: number;
  status: 'ready';
  provenance: {
    source: string;
    sourceExerciseId?: string;
    sourceCommit?: string;
    sourcePath?: string;
    license: string;
    attribution: string;
    commercialUseAllowed: boolean;
    redistributionAllowed: boolean;
    localBundleAllowed: boolean;
    referenceOnly: boolean;
    verification: {
      identity: 'verified' | 'unverified';
      rights: 'verified' | 'unverified' | 'restricted';
      asset: 'verified' | 'broken';
    };
  };
}

import registryJson from './generated-exercise-gifs.json';

export const GENERATED_EXERCISE_GIF_LIST: GeneratedExerciseGifRecord[] = registryJson as GeneratedExerciseGifRecord[];

/**
 * Fast O(1) lookup table indexed by canonical exercise ID
 */
export const GENERATED_EXERCISE_GIFS_BY_ID: Record<string, GeneratedExerciseGifRecord> =
  Object.fromEntries(GENERATED_EXERCISE_GIF_LIST.map((r) => [r.replyfExerciseId, r]));

/**
 * Fast O(1) lookup table indexed by canonical slug
 */
export const GENERATED_EXERCISE_GIFS_BY_SLUG: Record<string, GeneratedExerciseGifRecord> =
  Object.fromEntries(GENERATED_EXERCISE_GIF_LIST.map((r) => [r.canonicalSlug, r]));
